config/routes.rb
Diarioalimentaro::Application.routes.draw do
  resources :meals

  resources :meal_types

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
  belongs_to :meal_type
  attr_accessible :comments, :rating, :meal_type_id
  
  validates :user, :presence => true
end

app/models/meal_type.rb
class MealType < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :password
  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/meal_types_controller.rb
class MealTypesController < ApplicationController
  # GET /meal_types
  # GET /meal_types.json
  def index
    @meal_types = MealType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meal_types }
    end
  end

  # GET /meal_types/1
  # GET /meal_types/1.json
  def show
    @meal_type = MealType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal_type }
    end
  end

  # GET /meal_types/new
  # GET /meal_types/new.json
  def new
    @meal_type = MealType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal_type }
    end
  end

  # GET /meal_types/1/edit
  def edit
    @meal_type = MealType.find(params[:id])
  end

  # POST /meal_types
  # POST /meal_types.json
  def create
    @meal_type = MealType.new(params[:meal_type])

    respond_to do |format|
      if @meal_type.save
        format.html { redirect_to @meal_type, notice: 'Meal type was successfully created.' }
        format.json { render json: @meal_type, status: :created, location: @meal_type }
      else
        format.html { render action: "new" }
        format.json { render json: @meal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meal_types/1
  # PUT /meal_types/1.json
  def update
    @meal_type = MealType.find(params[:id])

    respond_to do |format|
      if @meal_type.update_attributes(params[:meal_type])
        format.html { redirect_to @meal_type, notice: 'Meal type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_types/1
  # DELETE /meal_types/1.json
  def destroy
    @meal_type = MealType.find(params[:id])
    @meal_type.destroy

    respond_to do |format|
      format.html { redirect_to meal_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new
    @meal_type = MealType.all.collect{|m| [m.name, m.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
    @meal_type = MealType.all.collect{|m| [m.name, m.id]}
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(params[:meal])
    @meal.user = User.find_by_id(1)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])
    @meal_type = MealType.all.collect{|m| [m.name, m.id]}

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meal_types_helper.rb
module MealTypesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diarioalimentaro</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meal_types/_form.html.erb
<%= form_for(@meal_type) do |f| %>
  <% if @meal_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal_type.errors.count, "error") %> prohibited this meal_type from being saved:</h2>

      <ul>
      <% @meal_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meal_types/edit.html.erb
<h1>Editing meal_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal_type %> |
<%= link_to 'Back', meal_types_path %>

app/views/meal_types/index.html.erb
<h1>Listing meal_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meal_types.each do |meal_type| %>
  <tr>
    <td><%= meal_type.name %></td>
    <td><%= link_to 'Show', meal_type %></td>
    <td><%= link_to 'Edit', edit_meal_type_path(meal_type) %></td>
    <td><%= link_to 'Destroy', meal_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meal type', new_meal_type_path %>

app/views/meal_types/new.html.erb
<h1>New meal_type</h1>

<%= render 'form' %>

<%= link_to 'Back', meal_types_path %>

app/views/meal_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meal_type.name %>
</p>


<%= link_to 'Edit', edit_meal_type_path(@meal_type) %> |
<%= link_to 'Back', meal_types_path %>

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meal_type %><br />
    <%= f.select :meal_type_id, @meal_type %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <tr>
    <th>User</th>
    <th>Meal type</th>
    <th>Rating</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.user %></td>
    <td><%= meal.meal_type.name %></td>
    <td><%= meal.rating %></td>
    <td><%= meal.comments %></td>
    <td><%= link_to 'Show', meal %></td>
    <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
    <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @meal.user %>
</p>

<p>
  <b>Meal type:</b>
  <%= @meal.meal_type.name %>
</p>

<p>
  <b>Rating:</b>
  <%= @meal.rating %>
</p>

<p>
  <b>Comments:</b>
  <%= @meal.comments %>
</p>


<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>